server:
  port: 10347

spring:
  application:
    name: xr-tiny
  profiles:
    active: dev

mybatis-plus:
  mapper-locations: classpath:/mapper/**/*.xml
  global-config:
    db-config:
      id-type: auto
      logic-delete-value: 1   # 逻辑删除值，配置注解@TableLogic，放入实体上
      logic-not-delete-value: 0
  configuration:
    auto-mapping-behavior: partial
    map-underscore-to-camel-case: true

jwt:
  tokenHeader: Authorization #JWT存储的请求头
  secret: mall #JWT加解密使用的密钥
  expiration: 604800 #JWT的超期限时间(60*60*24*7)
  tokenHead: 'Bearer '  #JWT负载中拿到开头

redis:
  database: xr
  key:
    admin: 'ums:admin'
    resourceList: 'ums:resourceList'
  expire:
    common: 86400 # 24小时

secure:
  ignored:
    urls: #安全路径白名单
      - /swagger-ui.html
      - /swagger-resources/**
      - /swagger/**
      - /**/v2/api-docs
      - /**/*.js
      - /**/*.css
      - /**/*.png
      - /**/*.ico
      - /webjars/springfox-swagger-ui/**
      - /actuator/**
      - /druid/**
      - /admin/login
      - /admin/register
      - /admin/info
      - /admin/logout
      - /minio/**
minio:
  endpoint: http://172.16.16.178:9000
  accessKey: xingruicompany
  secretKey: xingruicompany
  bucketName: test
### xxl-job admin address list, such as "http://address" or "http://address01,http://address02"
#xxl-job
xxl:
  job:
    admin:
      addresses: http://127.0.0.1:10899/xxl-job-admin
    executor:
      address: http://127.0.0.1:9999
      appname: spring-xxl-job
      ip: 127.0.0.1
      port: 9999
      logpath: ./log/xxlJobLog
      logretentiondays:  -1
    accessToken:


